### ISSUE TITLE
Tehtävät vko 8.-9./2017

### ISSUE THREAD

**Issue by v01ver** [ekoodi/ekoodi.github.io#9]
Ohjelmistotuotanto: 
- https://fi.wikipedia.org/wiki/Ohjelmistotuotanto
- https://www.cs.helsinki.fi/u/paakki/ohtuk03-luento3.pdf
- https://www.cs.helsinki.fi/u/paakki/
- oma rooli, motivaatio, kiinnostuksen kohteet

Scrum-projektinhallinta:
- Tutustuminen aiheeseen
- https://fi.wikipedia.org/wiki/Scrum
- Lean https://fi.wikipedia.org/wiki/Lean
- https://fi.wikipedia.org/wiki/Kanban

Vahti-ohjeistus:

- Vahti-ohjeistukseen tutustuminen
- https://www.vahtiohje.fi/web/guest
- Lokituksen määrittely https://www.vahtiohje.fi/web/guest/lokit-ja-lokityypit 
- Lokituksessa käytettävä kirjasto: https://logging.apache.org/log4net/
- https://www.vahtiohje.fi/web/guest/kayttajien-tunnistaminen-verkkopalveluissa

**Comment by v01ver** [comment]
Ohjelmistotuotanto linkki lisätty

**Comment by eaaho** [comment]
trello.com
